from base.base_exception_custom import BaseExceptionCustom


class NotFoundException(BaseExceptionCustom):
    pass